### PR TITLE
Update setup projects

### PR DESCRIPTION
**Pull request by vb2ae**
Updated setup projects to work with calibur.micro 4

### CODE REVIEW

**Comment by vb2ae** [comment]
@KasperSK I created an PR with updated setup projects

**Comment by KasperSK** [comment]
I am in the process of reviewing it, looks good so far.

**Comment by KasperSK** [comment]
@vb2ae The Setup solution looks good, I had no problems there in the Features solution I could not get the android project to run it said that IoC was not initialized, looks like the project is missing the setup of the IoC in the caliburn application so that might have been broken all along.
 In the Scenario solution I could not run the functional sample but I doubt that one is important.

**Review by KasperSK — APPROVED** [review]
Setup project works

**Pull request merged**
