### PR TITLE
Include bug #906 fix to V4

### PR DESCRIPTION
**Pull request by darxis**
This fixed bug #906 for the next V4 release.

@vb2ae Please publish V4.0.213 NuGet release, thanks.

### CODE REVIEW

**Review by vb2ae — CHANGES_REQUESTED** [review]
In Caliburn.Micro.Platform.cs could you change monoandroid80 to monoandroid90 (2 spots) to see if it builds.   If the samples or feature fail to build could you remove them from azure-pipeline.yml?

**Comment by darxis** [comment]
> In Caliburn.Micro.Platform.cs could you change monoandroid80 to monoandroid90 (2 spots) to see if it builds. If the samples or feature fail to build could you remove them from azure-pipeline.yml?

@vb2ae The build passes now, could you merge this and release V4.0.213 which includes this bugfix to NuGet please?

**Review by vb2ae — APPROVED** [review]

**Comment by vb2ae** [comment]
The fix is up on MyGet.  I will upload to NuGet when possible

**Comment by vb2ae** [comment]
@darxis I need to figure out this test issue in this pr https://github.com/Caliburn-Micro/Caliburn.Micro/pull/898 before I push to nuget

**Comment by Yinimi** [comment]
I think I've found the issue, the deactivation was called on the new item instead of the previous one
[commit on other pr](https://github.com/Caliburn-Micro/Caliburn.Micro/pull/898/commits/290c6512c72e3c8a7632f6cd67a5e81222e5034b)

**Comment by darxis** [comment]
@vb2ae Hi, would you release V4.0.213 on NuGet please?

**Comment by vb2ae** [comment]
@darxis sorry thought it went, got an error when deploying will fix

**Pull request merged**
