### PR TITLE
Reinstate XF package to make XF available on more platforms

### LINKED ISSUE #724: [Proposal] Restore the Caliburn.Micro.Xamarin.Forms NuGet package to enable XF on platforms other than iOS and Android
I would like to propose that we restore the `Caliburn.Micro.Xamarin.Forms` NuGet package as it was available in `3.2.0` and also in the first `4.0.0` alpha. 

My understanding as to why the package was removed was that the new SDK project model did not allow for including internal .dll's in a NuGet package. One Project = One Package with one dll (#707). 

However, I have looked into it and with some MSBuild tinkering it is possible to include an internal dll I have made an implementation in [My Fork](https://github.com/KasperSK/Caliburn.Micro)  on the master branch that demonstrates how we could restore the XF package this includes a SDK project dedicated to build the XF package but using linked files from the platform project. 

This is a breaking change so I would like to hear how you feel about this?

 @nigel-sampson, @vb2ae, @mbreckon, @CoreyVincent

### PR DESCRIPTION
**Pull request by KasperSK**
As discussed in #724 this pull request will reinstate the Xamarin.Forms package to allow for Xamarin.Forms on UWP or any other platform that Caliburn.Micro and Xamarin.Forms both support. 

Fixes #724

### CODE REVIEW

**Review by vb2ae — APPROVED** [review]

**Comment by nigel-sampson** [comment]
You'll need to make some modifications to the build pipeline so this project is built.

**Comment by KasperSK** [comment]
@nigel-sampson looking at the Azure-pipelines.yaml I thought that the projects to build was determined from the .sln file? And the packages are generated from passing the /pack flag? I looked in the log from the CI build and it looks like it builds the XF package.
So I am not really sure what needs to be changed can you point me in the right direction?

**Comment by KasperSK** [comment]
@nigel-sampson What is the status for this pull request? I am still not sure what I need to change in the build pipeline, I hope you find some time to guide me in the right direction.

**Comment by vb2ae** [comment]
@nigel-sampson any guidance on what we need to change to get this merged in?

**Comment by nigel-sampson** [comment]
Will review this one in depth in the new few days, been pretty busy recently.

**Comment by nigel-sampson** [comment]
Sorry about the delay on this, it looks good.  

Once the merge conflicts are fixed I'll merge it.

**Review by nigel-sampson — APPROVED** [review]

**Comment by KasperSK** [comment]
@nigel-sampson Conflicts should be fixed now.

**Comment by vb2ae** [comment]
thanks for merging

**Pull request merged**
