### PR TITLE
[wip] Action conventions for async methods

### PR DESCRIPTION
**Pull request by BrunoJuchli**
#154 
In addition to the existing matching, the following now works as well:
**Foo ==> Task FooAsync();**

- [x] implement Action Convention for async methods with `Async` suffix.
 - Wire `View.Foo` to `ViewModel.FooAsync()`
 - Wire guard of `View.FooAsync` to `ViewModel.CanFoo`
- [x] add a sample
- ~~write unit tests~~
- ~~write spec/integration tests~~

### CODE REVIEW

**Comment by BrunoJuchli** [comment]
What about unit & spec tests? As far as i can see there are no unit tests for `VIewModelBinder` as of yet.
Also, i couldn't find any integration tests which would instantiate a View and bind it to a view model. I'd like to have done that to check that the old conventions still work but the new one does too. Also in conjunction with guards.
Did i overlook something? Would you like me to write some - or rather not?

**Comment by nigel-sampson** [comment]
The unit tests aren't in a great shape, the latest version of xUnit has disabled the UI thread tests which need to fixed up in #157. Long term this is something that needs to be done a lot better. 

At the moment I'd add something to one of the samples as a bit of a test

**Comment by BrunoJuchli** [comment]
ok thx.
However i've just found that there was a misunderstanding.

You understood that "ViewModel.FooAsync()" should be wired to "View.Foo" (Foo => set by `x:Name=`) --> `ViewModelBinder.cs`.
However what i meant was is that the guard of "View.FooAsync" should be wired to "ViewModel.CanFoo" --> `ActionMessage.cs`.

Now i've implemented both but i'm thinking that the first part is not really necessary. It's only benefit is that it still works if i change between an async implementation (with  `Async` suffix) and a sync implementation (without `Async` suffix). On the downside it's slower and a bit more code to maintain.

The change to `ActionMessage.cs` is more important because it allows me to name a method `FooAsync` but the guard `CanFoo` (without suffix) as is called for by MS coding guidelines.

**Comment by nigel-sampson** [comment]
Ah yeah now I get you, personally I prefer both. Let me think on it and will let you know.

**Comment by nigel-sampson** [comment]
So I think we should include both, just looking over the diffs to keep consistent style and only a few minor things I noticed, some of it isn't your code as I've noticed it's not being consistent in the code base already but may as well kill two birds with one two and not force a merge issue.

- explicit private
- using var where possible
- I'd move the call to `BuildPossibleGuardNames` to inside `TryFindGuardMethod` rather than as a parameter.
- The indentation on `TryFindGuardMethod` looks a bit off.
- I think there's a line ending issue on the xaml file as the diff is a full replace.

Thanks again.

**Comment by BrunoJuchli** [comment]
ok thanks for your feedback. I'll implement the changes as soon as i can get to it :)

**Comment by BrunoJuchli** [comment]
@nigel-sampson 
ok i've implemented the changes and fixes to formatting.
However, i didn't move the call to `BuildPossibleGuardNames` because it's result are used in two places (`PrepareContext`, the method calling it, and `TryFindGuardMethod`).

**Comment by nigel-sampson** [comment]
Thanks, apologies for letting this one slip.

**Pull request merged**
