### PR TITLE
BindableCollection AddRange/RemoveRange NewItems/OldItems are now set

### PR DESCRIPTION
**Pull request by Yinimi**
When adding objects to a BindableCollection the e.NewItems in the CollectionChanged event used to be empty.

Current version:
image

Fixed version:
image

Code snipped:
[Program.txt](https://github.com/Caliburn-Micro/Caliburn.Micro/files/3206761/Program.txt)

### CODE REVIEW

**Comment by nigel-sampson** [comment]
Looks good, thanks, just need to do some legacy research. This is one of those changes that makes me wonder why it hasn't been done before.

**Comment by tibel** [comment]
be aware of https://github.com/dotnet/wpf/issues/1887

**Comment by Phyxion** [comment]
Just in case it might be useful: some collections (such as `ListCollectionView`) do not support ranged actions and throw. It works with `Reset`.

**Comment by Yinimi** [comment]
I rebased my fork and updated the code

**Comment by vb2ae** [comment]
@Yinimi Code looks good.  Need to do some testing this weekend

**Comment by vb2ae** [comment]
@KasperSK it is testing out ok.   What do you think about merging it in?

**Comment by KasperSK** [comment]
@vb2ae Could we test the case mentioned in [dotnet/wpf#1887](https://github.com/dotnet/wpf/issues/1887)? Seems bad if we could get runtime exceptions when running WPF.

**Comment by vb2ae** [comment]
Tested with this code

        public void btnChangeCollection()
        {
            Random rnd = new Random();
            var lst = new List<int>();
            for (int x = 0; x < 100; x++)
            {
                lst.Add(Numbers[x]);
            }

            Numbers.RemoveRange(lst);
            var lstToAdd = new List<int>();
            for (int z = 0; z < 100; z++)
            {
                lstToAdd.Add(rnd.Next(200000));
            }

            Numbers.AddRange(lstToAdd);
        }

Numbers was bound to a listbox.  AddRange and RemoveRange throw exceptions like @tibel  mentioned

image

**Comment by KasperSK** [comment]
Looks like we should not merge this before WPF has fixed the issue then.

**Pull request closed without merging**
