### PR TITLE
NameTransformer is faster with compiled Regex

### PR DESCRIPTION
**Pull request by Bobdina**
This is a heavily used codepath. I ran tests, compiled regex is faster (excluding first hit).
The first hit is about 8 times slower, but still a very low number (7 milliseconds on my machine).

### CODE REVIEW

**Comment by nigel-sampson** [comment]
Thanks, what's the performance difference on the subsequent calls?

**Comment by Bobdina** [comment]
For a 1000 calls, it's about 22ms to 11ms. I made a gist of the testrun I played with, so see for yourself: https://gist.github.com/Bobdina/48c7584627e77a01cf78

**Comment by nigel-sampson** [comment]
Thanks

**Comment by nigel-sampson** [comment]
Just a heads up on this one for next time that this broke the build on all platforms except WPF

**Comment by Bobdina** [comment]
Sorry, how did this break the build exactly?

**Comment by nigel-sampson** [comment]
`RegexOptions.Compiled` isn't a valid enum option in Silverlight and WinRT, but now is in UWP.

**Pull request merged**
