### PR TITLE
Moved FrameAdapter classes to separate files

### PR DESCRIPTION
**Pull request by neilt6**
I moved the `FrameAdapter` classes to their own files, rather than being combined with the `INavigationService` interfaces.

### CODE REVIEW

**Comment by neilt6** [comment]
@nigel-sampson For your consideration.

**Comment by vb2ae** [comment]
@neilt6 I will look at it tonight.  I do like the idea of not having more than one class in a file

**Comment by vb2ae** [comment]
it looks good

**Review by vb2ae — APPROVED** [review]
change looks good

**Pull request merged**
