### PR TITLE
Fix v4 azure build

### PR DESCRIPTION
**Pull request by darxis**
Azure pipeline build runs on `vmImage: windows-2019`.
Based on [windows-2019 vmImage readme](https://github.com/actions/runner-images/blob/main/images/windows/Windows2019-Readme.md) the minimum `Android SDK Platform` installed in this image is `android-30 (rev 3)`, that corresponds to Android 11 -> [source](https://developer.android.com/tools/releases/platforms).

To fix the Azure pipeline build in v4 we need to upgrade to Android 11 at least.

### CODE REVIEW

**Comment by vb2ae** [comment]
That was good idea changing the server type it runs on.

**Comment by vb2ae** [comment]
Looks you need to update the uwp cert

**Comment by darxis** [comment]
@vb2ae It builds now, please review

**Review by vb2ae — APPROVED** [review]
Looks good

**Comment by vb2ae** [comment]
Merged

**Pull request merged**
