### PR TITLE
468-469-470 Extend container functionality.

### PR DESCRIPTION
**Pull request by Stannieman**
This are the 3 last issues created by me.

### CODE REVIEW

**Comment by nigel-sampson** [comment]
Thanks for the PR, apologies for the delay in looking at all of this. I haven't looked too closely yet at the code, just the discussions.

Just to frame the conversation, I'm really hesitant to extend `SimpleContainer` too far, for a couple of reasons.

1. It stops becoming simple 😄 
2. A fully featured dependency injection container is a whole OSS project in itself and not something I want to do. Better to direct people to fully featured ones if they need something more powerful.

Having said that...

#467 This feels like an feature for a more fully featured framework and not for `SimpleContainer`.

#468 If I'm not mistaken this would be resolved by #469 if `EnablePropertyInjection` was true?

#469 Not sure about this one, it's definitely a breaking change, and I like that you've added it as a setting that's off by default.

#470 Appears to be an oversight given it will be injected as a constructor parameter so we should be consistent between the two. 

#472 Absolutely agree the change of singleton behavior would be a breaking change, it should probably be in it's own PR so other things can be merged without this holding it up. The points around a possible `RequiredDependency` and `DependencyKey` definitely feel like we're straying back to full on container land. Should be adding #374 as part of the next major version.

**Comment by nigel-sampson** [comment]
Thinking about this some more, rather than splitting into separate PR's we could shift it to the `dev/4.0.0` branch.

**Comment by Stannieman** [comment]
The RequiredDependency thing might be overkill actually when I look at it now. This is not really a "feature-feature". If a dependency annotated with it cannot be resolved (which the attribute tries to prevent) then this is actually a programming error. I don't think trying to fix this kind of errors is the container's job.
So let's forget about this feature :)

Then for the other features I proposed: The main reason is that I found the SimpleContainer to be just a little too simple. I started on a new application that is not complex at all, and still I found the current container to be too limited. And if it doesn't meet the requirements for an app of basic to mid complexity then I wonder how many use cases there are left for the current container.
I think adding these few features would make the container useful for a lot more projects.
- Property injection without BuildUp to not have constructors with 100 parameters.
- Recursive property injection to help with the feature above.
- Seeing the target type: example with logger.
- DependencyKey: SimpleContainer already has it but this is just to resolve contructor parameters/properties using the key also.

These things are currently blockers for me and the only reason I need to use a fully featured container.
I have a new container ready (need a few days to properly test it), then I will create a PR for it and you can choose to keep it in v4 or not.

**Comment by Stannieman** [comment]
@nigel-sampson I put together some container that is relatively simple but still suits all my needs and has the features of my previous tickets.
It's up [here](https://github.com/Stannieman/DI/). You can have a look and IF you want it then I'll create a PR for Caliburn 4 + add more testing, if not then I'll release it as a standalone package.

**Comment by nigel-sampson** [comment]
Thanks, I'll take a look but unlikely to switch containers at the point mainly due to the making a release with a lot of breaking changes even worse.

**Comment by xmedeko** [comment]
IMO the code of `BuildUp` in this PR should be merged to master, it does not break BC.
Further more, I recommend not to check `CanWrite && CanWrrite`, but to check: `property.SetMethod != null && !property.SetMethod.IsStatic`.

**Comment by nigel-sampson** [comment]
While the PR's can't be merged at the moment due to the changes in the 4.0.0 codebase, I plan to incorporate parts of these into the 4.0.0 release at some point.

**Comment by nigel-sampson** [comment]
Thanks for this PR, I've incorporated a lot from it.

**Pull request closed without merging**
