### PR TITLE
Update Caliburn.Micro.Platform.csproj

### PR DESCRIPTION
**Pull request by vb2ae**
move package reference to released version

### CODE REVIEW

**Review by nigel-sampson — APPROVED** [review]

**Comment by nigel-sampson** [comment]
Looks like the build is failing on this version

**Comment by vb2ae** [comment]
sorry about that undoing change

**Comment by nigel-sampson** [comment]
All good, no need to revert the change as this is only just a PR. it looks like the package version doesn't exist.

**Comment by Mrxx99** [comment]
The whole package was unlisted on nuget.org: https://www.nuget.org/packages/Microsoft.WindowsDesktop.App

**Comment by nigel-sampson** [comment]
Fun, assume there's a better replacement to use instead then?

**Comment by nigel-sampson** [comment]
Should the latest commit be on this branch / PR?

**Comment by vb2ae** [comment]
no removed it

**Pull request closed without merging**
