### PR TITLE
Strong-name all Assemblies

### PR DESCRIPTION
**Pull request by willson556**
Possible solution to #700
Tweaks for consistent strong-naming.
Also, reduced the number of targets required.

### CODE REVIEW

**Comment by nigel-sampson** [comment]
Reverted my commit, feel free to rebase, let's leave the target frameworks alone.

**Comment by nigel-sampson** [comment]
Although does having the different frameworks solve you issue?

**Comment by willson556** [comment]
Just finished testing and it works for me regardless of whether the frameworks change is present. Rebased as requested and removed the `TargetFrameworks` change in the `Caliburn.Micro.Core` project.

**Comment by nigel-sampson** [comment]
Thanks

**Pull request merged**
