### PR TITLE
Upgrade MSBuild.Sdk.Extras to 2.0.54

### PR DESCRIPTION
**Pull request by louistio**

### CODE REVIEW

**Comment by nigel-sampson** [comment]
Is this intended to resolve the current build failures?

**Comment by louistio** [comment]
Well it was an attempt at least 😅 Seems like there are other problems

**Comment by louistio** [comment]
The actual build seems to pass with this change, but there is a problem with `samples\features\Features.Forms\Features.Forms.Android\Resources\Resource.Designer.cs`. I didn't know these sample projects existed. 🤐

**Comment by nigel-sampson** [comment]
Yeah the `features` samples (but not the `setup`) projects build from the build output as a simple integration test.

**Comment by nigel-sampson** [comment]
Thanks for this even though it wasn't merged. 

Still need to dig into the features build issue.

**Comment by louistio** [comment]
No worries, I wish I could help more, I don't even have Xamarin dev tools installed and I've never done any before so I wouldn't even know where to start.

**Pull request closed without merging**
